export const data = [
  {
    ID: 1,
    IMAGE: 'https://via.placeholder.com/1000x800.png?text=Gambar',
    TITLE_ROOM: '201',
    LOCATION: 'Head Office ACC',
    FLOOR: '1',
    CAPACITY: 10,
    STATUS: true,
    ACTION: 'Edit',
  },
  {
    ID: 2,
    IMAGE: 'https://via.placeholder.com/1000x800.png?text=Gambar',
    TITLE_ROOM: '301',
    LOCATION: 'Berijalan',
    FLOOR: '1',
    CAPACITY: 9,
    STATUS: false,
    ACTION: 'Edit',
  },
  {
    ID: 3,
    IMAGE: 'https://via.placeholder.com/1000x800.png?text=Meeting Room',
    TITLE_ROOM: '301',
    LOCATION: 'Berijalan',
    FLOOR: '2',
    CAPACITY: 15,
    STATUS: true,
    ACTION: 'Edit',
  },
  {
    ID: 4,
    IMAGE: 'https://via.placeholder.com/1000x800.png?text=Pantry',
    TITLE_ROOM: '301',
    LOCATION: 'Berijalan',
    FLOOR: '3',
    CAPACITY: 1, // Can indicate unlimited capacity
    STATUS: true,
    ACTION: 'View',
  },
  {
    ID: 5,
    IMAGE: 'https://via.placeholder.com/1000x800.png?text=Server Room',
    TITLE_ROOM: '301',
    LOCATION: 'Head Office ACC',
    FLOOR: '1', // Can indicate basement level
    CAPACITY: 1,
    STATUS: true,
    ACTION: 'Restricted',
  },
  {
    ID: 6,
    IMAGE: 'https://via.placeholder.com/1000x800.png?text=Storage',
    TITLE_ROOM: '301',
    LOCATION: 'Head Office ACC',
    FLOOR: '1',
    CAPACITY: 20,
    STATUS: false, // Can indicate inactive or unavailable
    ACTION: 'Edit',
  },
  {
    ID: 7,
    IMAGE: 'https://via.placeholder.com/1000x800.png?text=Relaxation',
    TITLE_ROOM: '301',
    LOCATION: 'Head Office ACC',
    FLOOR: '2',
    CAPACITY: 8,
    STATUS: true,
    ACTION: 'View',
  },
]
